# Generated by Django 3.2 on 2023-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_person_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
